explore_node:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: true
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: false
    planner_frequency: 0.2
    progress_timeout: 15.0
    potential_scale: 5.0
    orientation_scale: 0.5
    gain_scale: 1.0
    transform_tolerance: 0.1
    min_frontier_size: 0.6