
### This base is copied to $AIIL_CHECKOUT_DIR/.basrhc by the build_setup script ###

# Aliases
alias grep='grep --color=auto'
alias vi="vim"
alias ..="cd .."

# Dir Stack
function pn_stack()
{
    lines=`dirs | wc -w | sed -E -e 's/ +//'`
    lines=`expr $lines - 1`
    echo
    echo "Dir Stack"
    dirs -v | tail -$lines | sort -rn | sed -e 's/^/    /'
}

function pn_pushd()
{
    pushd $1 > /dev/null;
    pn_stack
}

alias pd='pn_pushd'
alias pp='popd > /dev/null; pn_stack'


######## ROS2

function rosenv() {
    printenv | grep 'ROS'
}

function set_ros_domain() {
    ros2 daemon stop
    if [[ $# -eq 0 ]] ; then
        unset ROS_DOMAIN_ID
    else
        export ROS_DOMAIN_ID=`$AIIL_CHECKOUT_DIR/bin/get_robot_info.py -r $1 -i -q`
    fi
    echo "Setting: ROS_DOMAIN_ID=$ROS_DOMAIN_ID"
    ros2 daemon start
}

# ROS Environment Variables
export ROS_LOCALHOST_ONLY=0

# Block setup.py waning
export PYTHONWARNINGS="ignore:easy_install command is deprecated,ignore:setup.py install is deprecated"

# Configure DDS
unset FASTRTPS_DEFAULT_PROFILES_FILE
unset CYCLONEDDS_URI
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
# export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
export FASTRTPS_DEFAULT_PROFILES_FILE=$AIIL_CHECKOUT_DIR/config/dds/rmit-fastrtps-dds.xml
# export CYCLONEDDS_URI=file://$AIIL_CHECKOUT_DIR/config/dds/rmit-cyclone-dds.xml

######## ROS1 
# ROS Parameter Settings
#unset ROS_IPV6
#unset ROS_HOSTNAME
#export ROS_HOSTNAME=`hostname`

# Function to set master
# function set_ros_master() {
#     export ROS_MASTER_URI=http://$1:11311
#     echo "Setting: ROS_MASTER_URI=$ROS_MASTER_URI"
# }

# Set ROS IP using default (or provided) argument
# function set_ros_ip() {
#     unset ROS_HOSTNAME
#     if [[ $# -eq 0 ]] ; then
#         export ROS_IP=`hostname -I | awk '{print $1}'`
#     else
#         export ROS_IP=$1
#     fi
#     echo "Unset: ROS_HOSTNAME"
#     echo "Setting: ROS_IP=$ROS_IP"
# }

# Set ROS HOSTNAME using default (or provided) argument
# function set_ros_hostname() {
#     unset ROS_IP
#     if [[ $# -eq 0 ]] ; then
#         export ROS_HOSTNAME=`hostname`
#     else
#         export ROS_HOSTNAME=$1
#     fi
#     echo "Unset: ROS_IP"
#     echo "Setting: ROS_HOSTNAME=$ROS_HOSTNAME"
# }

# Ensure root ROS is sourced
source /opt/ros/humble/setup.bash

#### END BASE ####
