# Comments:
#   * This is a temporary solution allowing shared memory communication between host and docker container when
#     using Fast DDS. To be removed when user will be able to change this permission to something else than 0644 
#     (https://github.com/eProsima/Fast-DDS/blob/master/thirdparty/boost/include/boost/interprocess/permissions.hpp#L100) 
#
#  ** If the FASTRTPS_DEFAULT_PROFILES_FILE or CYCLONEDDS_URI envs are defined, then we need to bind mount the volume
#     with the DDS config to the container  
#
# *** Optional envs the ROS user may want to set - we need to pass them to the container

x-common-config:
  &common-config
  restart: unless-stopped
  network_mode: host
  ipc: host
  user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # *


services:
  astra:
    image: husarion/astra:humble
    container_name: astra
    extends:
      file: /home/husarion/aiil_workspace/docker/rosbot/compose-common.yaml
      service: astra
    <<: *common-config
    profiles: ["all"]
    devices:
      - /dev/bus/usb/
    command: ros2 launch astra_camera astra_mini.launch.py

  rplidar:
    image: husarion/rplidar:humble
    container_name: rplidar
    extends:
      file: /home/husarion/aiil_workspace/docker/rosbot/compose-common.yaml
      service: rplidar
    <<: *common-config
    profiles: ["all"]
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: >
        ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE:-256000}

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    container_name: microros
    extends:
      file: /home/husarion/aiil_workspace/docker/rosbot/compose-common.yaml
      service: microros
    <<: *common-config
    profiles: ["all"]
    devices:
      - ${SERIAL_PORT:?err}
    environment: #only two envs are valid for micro-xrce-agent
      - FASTRTPS_DEFAULT_PROFILES_FILE            # ***
      - XRCE_DOMAIN_ID_OVERRIDE=${ROS_DOMAIN_ID:-}  # ***
    command: MicroXRCEAgent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rosbot:
    # image: husarion/rosbot:humble-0.6.1-20230712
    # image: husarion/rosbot:humble-0.13.1-20240207
    image: husarion/rosbot:humble-0.11.1-20231229
    container_name: rosbot
    extends:
      file: /home/husarion/aiil_workspace/docker/rosbot/compose-common.yaml
      service: rosbot
    <<: *common-config
    profiles: ["all"]
    command: ros2 launch rosbot_bringup bringup.launch.py

  slam_toolbox:
    image: husarion/slam-toolbox:humble
    container_name: slam_toolbox
    <<: *common-config
    extends:
      file: /home/husarion/aiil_workspace/docker/rosbot/compose-common.yaml
      service: slam_toolbox
    profiles: ["all"]
    volumes:
      - /home/husarion/aiil_workspace/humble_workspace/src/aiil_rosbot_demo/config/slam.yaml:/slam_params/slam.yaml
    command: ros2 launch slam_toolbox online_sync_launch.py slam_params_file:=/slam_params/slam.yaml use_sim_time:=false

  nav2:
    image: husarion/navigation2:humble
    container_name: nav2
    extends:
      file: /home/husarion/aiil_workspace/docker/rosbot/compose-common.yaml
      service: slam_toolbox
    <<: *common-config
    profiles: ["all"]
    # profiles: ["nav"]
    volumes:
      - /home/husarion/aiil_workspace/humble_workspace/src/aiil_rosbot_demo/config/navigation_pro2.yaml:/nav2_params/params.yaml
      - /home/husarion/aiil_workspace/humble_workspace/src/aiil_rosbot_demo/config/aiil_simple_navigate.xml:/nav2_params/nav_bt.xml
    command: ros2 launch nav2_bringup navigation_launch.py params_file:=/nav2_params/params.yaml use_sim_time:=false

  # RMIT workspace is not launched, just make a bash container
  rmit_aiilworkspace:
    image: rmit/aiil_workspace
    container_name: rmit_aiilworkspace
    extends:
      file: /home/husarion/aiil_workspace/docker/rosbot/compose-common.yaml
      service: rmit_aiilworkspace
    <<: *common-config
    profiles: ["aiil"]
    volumes:
      - /home/husarion/aiil_workspace/humble_workspace:/ros2_ws
    # command: ros2 launch rosbot_bringup bringup.launch.py


volumes:
  dummy_volume_fastdds:
  dummy_volume_cyclonedds:

