# Comments:
#   * This is a temporary solution allowing shared memory communication between host and docker container when
#     using Fast DDS. To be removed when user will be able to change this permission to something else than 0644 
#     (https://github.com/eProsima/Fast-DDS/blob/master/thirdparty/boost/include/boost/interprocess/permissions.hpp#L100) 
#
#  ** If the FASTRTPS_DEFAULT_PROFILES_FILE or CYCLONEDDS_URI envs are defined, then we need to bind mount the volume
#     with the DDS config to the container  
#
# *** Optional envs the ROS user may want to set - we need to pass them to the container
#
#   + Required to ensure docker is run with the correct user id

x-volumes-config:
  &common-volumes
  volumes:
    - /etc/group:/etc/group:ro                  # *
    - /etc/passwd:/etc/passwd:ro                # *
    - /etc/shadow:/etc/shadow:ro                # *
    - /home/husarion/.ros:/home/husarion/.ros   # *
    - ${FASTRTPS_DEFAULT_PROFILES_FILE:-dummy_volume_fastdds}:${FASTRTPS_DEFAULT_PROFILES_FILE:-/dummy_volume_fastdds}:ro  # **
    # - ${CYCLONEDDS_PATH:-dummy_volume_cyclonedds}:${CYCLONEDDS_PATH:-/dummy_volume_cyclonedds}:ro                          # **
    - /home/husarion/aiil_workspace/config/dds/rmit-fastrtps-dds.xml:/rmit-fastrtps-dds.xml
    - /home/husarion/aiil_workspace/config/dds/rmit-cyclone-dds.xml:/rmit-cyclone-dds.xml

x-environment-config:
  &common-environment
  environment:
    - RMW_IMPLEMENTATION              # ***
    - FASTRTPS_DEFAULT_PROFILES_FILE=/rmit-fastrtps-dds.xml  # ***
    # - CYCLONEDDS_URI=file:///rmit-cyclone-dds.xml                  # ***
    - ROS_DOMAIN_ID                   # ***
    - ROS_LOCALHOST_ONLY
    - USER        
    - AIIL_CHECKOUT_DIR=/ros2_ws                    # +


services:
  astra:
    <<: [*common-volumes, *common-environment]

  rplidar:
    <<: [*common-volumes, *common-environment]

  microros:
    <<: [*common-volumes, *common-environment]
  
  oakd:
    <<: [*common-volumes, *common-environment]

  rosbot:
    <<: [*common-volumes, *common-environment]

  slam_toolbox:
    <<: [*common-volumes, *common-environment]

  rmit_aiilworkspace:
    <<: [*common-volumes, *common-environment]

volumes:
  dummy_volume_fastdds:
  dummy_volume_cyclonedds:
